FROM golang:1.22-alpine3.19

WORKDIR /app

COPY . .

ENV FROM_EMAIL=${FROM_EMAIL}
ENV PASSWORD_EMAIL=${PASSWORD_EMAIL}
ENV TO_EMAIL=${TO_EMAIL}
ENV SMTP_HOST=${SMTP_HOST}
ENV SMTP_PORT=${SMTP_PORT}
ENV APP_PORT=${APP_PORT}

CMD ["go", "run", "main.go"]
